version: 2.1
jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.33.0-focal
    resource_class: medium
    steps:
      - checkout
      - run: npm ci
      - run: npm test
      - store_test_results:
          path: test-results.xml
      - store_artifacts:
          path: playwright-report
workflows:
  build_and_test:
    jobs:
      - test
